#!/bin/bash

src_dotfiles_dir=$(dirname "$(realpath "$0")")

function create_symlinks() {
    local dot_files=(".vimrc" ".gitconfig" ".bash_aliases")

    for dot_file in "${dot_files[@]}"
    do
        if [ -L "$HOME/$dot_file" ];
        then
            continue
        fi

        if [ -e "$HOME/$dot_file" ];
        then
            local backup_file="$HOME/${dot_file}_bk_$(date +%Y_%m_%d_%H%M%S)"
            cp "$HOME/$dot_file" "$backup_file"
            rm "$HOME/$dot_file"
            echo "$HOME/$dot_file has been backed up to $backup_file"
        fi

        echo "Creating symlink $HOME/$dot_file for target $src_dotfiles_dir/$dot_file"
        ln -s "$src_dotfiles_dir/$dot_file" "$HOME/$dot_file"
    done
}

function update_bashrc_from_template {
    local start_marker=$(awk '/# <<< START AUTOGEN/ {print FNR}' $HOME/.bashrc)
    local end_marker=$(awk '/# <<< END AUTOGEN/ {print FNR}' $HOME/.bashrc)

    if [ ${#start_marker} -ne 0 ] && [ ${#end_marker} -ne 0 ];
    then
        echo 'removing previous autogen content from ~/.bashrc'
        $(sed -i ${start_marker},${end_marker}d $HOME/.bashrc)
    fi

    echo '# <<< START AUTOGEN' >> $HOME/.bashrc
    cat $src_dotfiles_dir/.bashrc_template >> $HOME/.bashrc
    echo '# <<< END AUTOGEN' >> $HOME/.bashrc
}

create_symlinks
update_bashrc_from_template
